# Generated by Django 4.0.2 on 2022-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='opportunities/images/')),
                ('type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('training', 'Training'), ('course', 'Course')], default='seminar', max_length=20)),
                ('category', models.CharField(choices=[('per_dev', 'Personal Development'), ('marketing', 'Marketing'), ('startups', 'Startups')], default='per_dev', max_length=20)),
                ('online', models.BooleanField()),
                ('cta_link', models.URLField()),
                ('organizer', models.CharField(max_length=200)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
